name: amrita_vidyalyam_admission
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.3
  riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  go_router: ^17.0.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.2
  lottie: ^3.3.2
  dio: ^5.9.0
  skeletonizer: ^2.1.0+1
  lucide_icons_flutter: ^3.1.6
  intl: ^0.20.2
  aad_oauth: ^1.0.1
  flutter_secure_storage: ^9.2.4
  jwt_decode: ^0.3.1
  google_fonts: ^6.3.3
  pinput: ^3.0.0
  easebuzz_flutter_sdk: ^1.0.1
  pdf: ^3.11.3
  printing: ^5.14.2
  path_provider: ^2.1.5
  open_file: ^3.5.10
  url_launcher: ^6.3.2
  change_app_package_name: ^1.5.0
  connectivity_plus: ^7.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^3.0.3
  build_runner: ^2.10.4
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#0B3160"
  adaptive_icon_foreground: "assets/images/app_icon.png"
