name: amrita_vidhyalayam_admission
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0-158.0.dev

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.6.1

  # Navigation
  go_router: ^14.6.0

  # Networking
  dio: ^5.7.0

  # Data Class / JSON Serialization
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # Local Storage
  shared_preferences: ^2.3.3

  # UI & Utilities
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  logger: ^2.5.0
  intl: ^0.19.0
  flutter_svg: ^2.0.16
  flutter_screenutil: ^5.9.3
  lucide_icons_flutter: ^3.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
